### ISSUE TITLE
关于模型训练

### ISSUE THREAD

**Issue by yaoing** [lhr0909/rasa-chinese-paddlenlp#4]

**Comment by lhr0909** [comment]
> 作者你好, 我看了下paddlenlp_tokenizer和paddlenlp_featurizer代码里没有关于训练的描述, 是不是说明预训练模型没有办法直接通过rasa的NLU example进行微调呢?

@yaoing 你好，Rasa的实现原理是使用预训练模型的embedding进行DIET Classifier的训练，所以不直接对预训练模型进行训练哈。如果有微调需求的话，需要参考PaddleNLP提供的办法先对模型进行微调，再在Rasa中使用。希望可以帮到你。

**Comment by yaoing** [comment]
是的, 我今天刚了解到了, 所以关了issue~

**Comment by yaoing** [comment]
另外, 顺便请教一下, DIET Classifier的epoch一般设置多大呢?
